services:
  api:
    build: .
    container_name: spark-apply-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ajii/manifest:/services
    environment:
      - BASE_FOLDER=/services
    networks:
      - pipeline-net

networks:
  pipeline-net:
    external: true