services:
  api:
    build: .
    container_name: spark-apply-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BASE_FOLDER=/Users/ajii/Documents/spark-apply/services
